#' Simplify a list to a single SingleCellExperiment
#'
#' Simplify a list of \linkS4class{SingleCellExperiment}, usually generated by \code{\link{applySCE}} on main and alternative Experiments,
#' into a single SingleCellExperiment containing some of the results in its \code{\link{altExps}}.
#'
#' @param results A list of SummarizedExperiment or SingleCellExperiment objects.
#' @param which A list of \linkS4class{SCEInput} objects of the same length as \code{results}.
#' This should be of the same length as that used to construct \code{results}.
#' @param x The original SingleCellExperiment from which \code{results} were computed.
#' @param warn.level Integer scalar specifying the type of warnings that can be emitted.
#'
#' @return 
#' A SingleCellExperiment corresponding to the entry of \code{results} generated from any part of the main Experiment of \code{x}.
#' All results generated from the alternative Experiments of \code{x} are stored in the \code{\link{altExps}} of the output.
#' 
#' Alternatively, if simplification could not be performed, \code{NULL} is returned with a warning (depending on \code{warn.level}.
#'
#' @author Aaron Lun
#'
#' @details
#' Each entry of \code{results} should have the same number and names of the columns.
#' 
#' In \code{which}, there should be no more than one entry that extracts data from the main Experiment 
#' (e.g., a \linkS4class{MainExpInput}, \linkS4class{AssayInput} or \linkS4class{ReducedDimInput}).
#' If one exists, the corresponding entry of \code{results} should be a SingleCellExperiment and is then used as the main Experiment in the output.
#' Otherwise, if no such entry of \code{which} exists, an empty SingleCellExperiment is constructed as a container for the \code{\link{altExps}}.
#'
#' In \code{which}, there should be no more than one reference to each alternative Experiment in \code{x}.
#' For each reference, the corresponding entry of \code{results} is stored in the \code{\link{altExps}} of the output under the same name that was used in \code{x}.
#'
#' The type of warnings that are emitted can be controlled with \code{warn.level}.
#' If \code{warn.level=0}, no warnings are emitted.
#' If \code{warn.level=1}, all warnings are emitted except for those related to \code{results} not being of the appropriate class.
#' If \code{warn.level=2}, all warnings are emitted, and if \code{warn.level=3}, warnings are promoted to errors.
#'
#' @examples
#' ncells <- 100
#' u <- matrix(rpois(20000, 5), ncol=ncells)
#' pca <- matrix(runif(ncells*5), ncells)
#' sce <- SingleCellExperiment(assays=list(counts=u),
#'     reducedDims=SimpleList(PCA=pca))
#' altExp(sce, "BLAH") <- SingleCellExperiment(assays=list(counts=u*10),
#'     reducedDims=SimpleList(PCA=pca/10))
#' altExp(sce, "WHEE") <- SingleCellExperiment(assays=list(counts=u*2),
#'     reducedDims=SimpleList(PCA=pca/5))
#'
#' # Setting FUN=identity just extracts each piece:
#' which <- list(MainExpInput(), AltExpInput("BLAH"), AltExpInput("WHEE"))
#' results <- applySCE(sce, FUN=identity, SIMPLIFY=FALSE, which=which)
#' results
#' 
#' # Simplifying to an output that mirrors the structure of 'sce'.
#' simplifyToSCE(results, which, sce)
#' 
#' @seealso
#' \code{\link{applySCE}}, where this function is used when \code{SIMPLIFY=TRUE}.
#' 
#' @export
#' @importFrom S4Vectors make_zero_col_DFrame
simplifyToSCE <- function(results, which, x, warn.level=2) {
    N <- length(which)
    stopifnot(length(results)==N)

    if (warn.level==3) {
        WTFUN <- stop
    } else if (warn.level==0) {
        WTFUN <- identity
    } else {
        WTFUN <- warning
    }

    # Checking that simplification is possible.
    ae.name <- rep(NA_character_, N)

    for (i in seq_len(N)) {
        curin <- which[[i]]

        if (isInputAltExp(curin)) {
            exp <- curin@experiment
            if (is.numeric(exp)) {
                exp <- names[exp]
            }
            ae.name[i] <- exp
        }

        curres <- results[[i]]
        if (!is(curres, "SummarizedExperiment")) {
            if (warn.level > 1) {
                WTFUN("could not simplify as result ", i, " is not a SummarizedExperiment")
            }
            return(NULL)
        } 
    }

    main <- which(is.na(ae.name))
    if (length(main) > 1) {
        WTFUN(paste(strwrap("could not simplify results due to multiple references to the main Experiment in 'which'"), collapse="\n"))
        return(NULL)
    }

    if (dup <- anyDuplicated(ae.name)) {
        WTFUN(paste(strwrap(paste0("could not simplify results due to multiple references to the '", ae.name[dup], "' alternative Experiment in 'which'")), collapse="\n"))
        return(NULL)
    }

    u.ncols <- unique(lapply(results, ncol))
    u.colnames <- unique(lapply(results, colnames))
    if (length(u.ncols)!=1 || length(u.colnames)!=1) {
        if (warn.level > 0) {
            WTFUN("could not simplify results as the columns are different")
        }
        return(NULL)
    }

    if (length(main)) {
        sce <- results[[main]]
        if (!is(sce, "SingleCellExperiment")) {
            if (warn.level > 1) {
                WTFUN("entry of 'results' corresponding to main Experiment is not a SingleCellExperiment")
            }
            return(NULL)
        }
    } else {
        df <- make_zero_col_DFrame(nrow=u.ncols[[1]])
        rownames(df) <- u.colnames[[1]]
        sce <- SingleCellExperiment(colData=df)
    }

    for (a in which(!is.na(ae.name))) {
        altExp(sce, ae.name[a]) <- results[[a]]
    }

    sce
}
